[window]
window_background = "#11111b"

[header]
header_background = "#313244"
header_text = "#7f849c"

[text]
ui_text = "#a6adc8"
ui_selected_text = "#74c7ec"
ascii_title = "#89b4fa"
icons = "#89b4fa"

[cube]
cube_top = "#cdd6f4" 
cube_bottom = "#f9e2af"
cube_left = "#a6e3a1"
cube_right = "#89b4fa"
cube_front = "#f38ba8"
cube_back = "#fab387"
