[window]
window_background = "rgb(24, 25, 38)"
side_pane_backgroundr = ""
icon_color = ""

[header]
header_background = ""
header_text = ""

[text]
ui_text = ""
ui_selected_text = "rgb(125, 196, 228)"
ascii_title = ""

[cube]
cube_top = "rgb(202, 211, 245)" 
cube_bottom = "rgb(238, 212, 159)"
cube_left = "rgb(166, 218, 149)"
cube_right = "rgb(138, 173, 244)"
cube_front = "rgb(237, 135, 150)"
cube_back = "rgb(245, 169, 127)"
