[window]
window_background = "#24292e"

[header]
header_background = "#2b3137"
header_text = "#6e738d"

[text]
ui_text = "#939ab7"
ui_selected_text = "#52dbbd"
ascii_title = "#55d0db"
icons = "#b1e8fd"

[cube]
cube_top = "#fafbfc" 
cube_bottom = "#f2c35c"
cube_left = "#2dba4e"
cube_right = "#0d74e7"
cube_front = "#f0440a"
cube_back = "#f5a97f"
