[window]
window_background = "#282c34"

[header]
header_background = "#32363e"
header_text = "#636d83"

[text]
ui_text = "#abb2bf"
ui_selected_text = "#56b6c2"
ascii_title = "#528bff"
icons = "#c678dd"

[cube]
cube_top = "#f2f4f5" 
cube_bottom = "#e5cb6f"
cube_left = "#98c379"
cube_right = "#61afef"
cube_front = "#d74a50"
cube_back = "#df8735"
