[window]
window_background = ""
side_pane_backgroundr = ""

[header]
header_background = ""
header_text = ""

[text]
ui_text = ""
ui_selected_text = ""
icon_color = ""
ascii_title = ""

[cube]
cube_top = "" 
cube_bottom = ""
cube_left = ""
cube_right = ""
cube_front = ""
cube_back = ""
