[ui_display]
show_background = true
show_headers = true
show_ui_borders = false
color_scheme = "Tokyonight"
ascii_banner = "default"

[controls]
nav_left = "arw"
nav_right = "arw"
nav_up = "arw"
nav_down = "arw"
rotate_clockwise = "arw"
rotate_counter_clockwise = "arw"
alt_nav_left = "h"
alt_nav_right = "l"
alt_nav_up = "k"
alt_nav_down = "j"
alt_rotate_clockwise = "h"
alt_rotate_counter_clockwise = "l"
