[ui_display]
show_background = true
show_headers = true
show_ui_borders = true
color_scheme = "Catppuccin-Macchiato"
ascii_banner = "Slant"

[audio]
enable_sound_effects = true

[controls]
alt_keys = "Vim"
