name: ci-cd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RELEASE_VERSION: v0.0.1
  RELEASE_NOTES: "New release for version ${{ github.run_number }}"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - name: Test with pytest
      run: |
        pytest
    - name: Create source code archive
      run: |
        tar -czf source-code.tar.gz ./src ./conf ./data
        zip -r source-code.zip ./src ./conf ./data
    - name: Configure Git identity
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Create Git tag
      run: git tag -a "v${{ github.run_number }}" -m "Release version v${{ github.run_number }}"
    - name: Push Git tag
      run: git push origin "v${{ github.run_number }}"
    - name: Create GitHub release and upload assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          source-code.tar.gz
          source-code.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
