name: Run Tests

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - name: Test with pytest
      run: |
        pytest 
    
    - name: Test Makefile on macOS
      if: matrix.os == 'macos-latest'
      run: make
      shell: bash
    
    - name: Run installed application
      if: matrix.os == 'macos-latest'
      run: |
        echo "Checking binary location:"
        ls -l /usr/local/bin/games-tui
        echo "Running games-tui..."
        /usr/local/bin/games-tui --version
      shell: bash
