name: Run Tests

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "master", "development" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Test with pytest
      run: |
        pytest
      shell: bash

    - name: Test Makefile on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        set -x
        make install
        make build
        make install_binary
        echo "Checking installed binary..."
        ls -l /usr/local/bin/games-tui || echo "Binary not found!"
        
        echo "Checking installation directory..."
        ls -l /usr/local/lib/games-tui/config || echo "Config data not found!"
        ls -l /usr/local/lib/games-tui/data || echo "App data not found!"

        games-tui || echo "Failed running the application."
      shell: bash

    - name: Test Makefile on macOS
      if: matrix.os == 'macos-latest'
      run: |
        set -x
        make install
        make build
        make install_binary
        echo "Checking installed binary..."
        ls -l /usr/local/bin/games-tui || echo "Binary not found!"
        
        echo "Checking installation directory..."
        ls -l /usr/local/lib/games-tui/config || echo "Config data not found!"
        ls -l /usr/local/lib/games-tui/data || echo "App data not found!"

        games-tui || echo "Failed running the application."
      shell: bash

    - name: Test Makefile on Windows
      if: matrix.os == 'windows-latest'
      run: |
        set -x
        make install
        make build
        make install_binary
        echo "Checking installed binary..."
        dir C:\Program\ Files\games-tui\games-tui.exe || echo "Binary not found!"

        echo "Checking installation directory..."
        dir C:\Program\ Files\games-tui\config || echo "Config data not found!"
        dir C:\Program\ Files\games-tui\data || echo "App data not found!"
        
        games-tui || echo "games-tui failed to run"
      shell: bash


